name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Cancel any in-flight jobs for the same PR/branch so there's only one active
# at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup Emscripten
        run: |
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          ./emsdk install latest
          ./emsdk activate latest
      - name: Download SHDC
        run: |
          curl https://raw.githubusercontent.com/floooh/sokol-tools-bin/3592dabe8667d0ef3c36fa9bcce903a9aa9e8b46/bin/linux/sokol-shdc -o sokol-shdc
          chmod +x sokol-shdc
          pwd >> $GITHUB_PATH
      - name: Build native
        run: |
          cd native
          cmake -B build -DCMAKE_TOOLCHAIN_FILE=../emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
          cmake --build build
      - name: Build scripts
        run: |
          cd script
          npm install
          npm run build
      - name: Build site
        run: |
          npm install
          npm run build
      - name: Run tests
        run: python3 tests/compile-examples.py
